# Generated by Django 2.1.7 on 2019-02-12 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='twits', to=settings.AUTH_USER_MODEL),
        ),
    ]
